### ISSUE TITLE
Improve the format of the `timestamp` property to conform to "hh:mm:ss.sss"

### ISSUE THREAD

**Issue by MatusGasparik** [ES-Alexander/pythonic-cv#19]
Currently, if I call `timestamp` on `VideoReader` instance, say somewhere after the minute 8, I get the following output:

```
'8.0:15.320'
```

whereas it would be ideal to have it in the format:

```
'08:15.320'
```

...as it would conform to the ISO 8601 standard of "HH:MM:SS.SSS" and would be a lot easier to read when used in filenames.

These would be the necessary changes to fix in [src/pcv/vidIO.py](https://github.com/ES-Alexander/pythonic-cv/blob/7f83516f87307c5c09e87618ac663b97d039af3b/src/pcv/vidIO.py#L1012)

```python
@property
def timestamp(self):
    ''' Returns the video timestamp if possible, else 0.0.

    Returns a human-readable time string, as hours:minutes:seconds.
    For the numerical ms value use self.get('timestamp') instead.

    self.timestamp -> str

    '''
    # cv2.VideoCapture returns ms timestamp -> convert to meaningful time
    seconds          = self.get('timestamp') / 1000
    minutes, seconds = divmod(seconds, 60)
    hours, minutes   = divmod(minutes, 60)
    if hours:
        return f'{int(hours):02d}:{int(minutes):02d}:{seconds:06.3f}'
    if minutes:
        return f'{int(minutes):02d}:{seconds:06.3f}'
    return f'{seconds:06.3f}s'
```

**Comment by ES-Alexander** [comment]
I ended up out the timestamps earlier today, so it’s all good for now. I also added you as a contributor in the README since you’ve made multiple helpful recommendations :-)

Haha, not forced to stay in bed - it was just late at night time and I was meant to be asleep (like now 😂)
